#if !canImport(ObjectiveC)
import XCTest

extension JapaneseNationalHolidaysTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JapaneseNationalHolidaysTests = [
        ("test_holidayNames", test_holidayNames),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JapaneseNationalHolidaysTests.__allTests__JapaneseNationalHolidaysTests),
    ]
}
#endif
